---
# OPEN WORLD PM64 SETTINGS
SettingsName   : Default Dev Preset
SettingsVersion: 0.1

# Options
StartingMap         : 0x00010104 # mac_00, Entry4
BlocksMatchContent  : true
AlwaysSpeedySpin    : true
AlwaysISpy          : false
AlwaysPeekaboo      : false
HiddenBlockMode     : 1
AllowPhysicsGlitches: false

StartingCoins: 50
CapEnemyXP   : true
NoXP         : false
2xDamage     : false
4xDamage     : false
OHKO         : false
NoSaveBlocks : false
NoHeartBlocks: false

# Pre-opened areas
FlowerGateOpen: false
BlueHouseOpen : false
ToyboxOpen    : false
WhaleOpen     : false

# Randomization: Logic
PlacementAlgorithm: ForwardFill
#PlacementAlgorithm: WeightedForwardFill # NYI
#PlacementAlgorithm: AssumedFill # NYI
#PlacementAlgorithm: CustomSeed
PlacementLogic: NoGlitches
#PlacementLogic: Glitches # NYI
#PlacementLogic: NoLogic

# Randomization: Difficulty
ShuffleChapterDifficulty: false
ProgressiveScaling      : false
RandomFormations        : false

# Randomization: Items
ShuffleItems          : true
IncludeCoins          : false
IncludeShops          : true
IncludePanels         : true
IncludeDojo           : false
IncludeFavors         : false # Koopa Koot Favors
IncludeLetterChain    : false # true -> NYI
KeyitemsOutsideDungeon: false
KeyitemsOutsideChapter: true # "Keysanity" # false -> NYI

# Randomization: Moves and Badges
ShuffleBadgesBP   : false
ShuffleBadgesFP   : false
ShufflePartnerFP  : false
ShuffleStarpowerSP: false

# Randomization: Entrances
ShuffleEntrances        : true  # NYI
ShuffleEntrancesByArea  : true  # NYI
ShuffleEntrancesByAll   : false # NYI
MatchEntranceTypes      : true  # NYI
RandomizeOnewayEntrances: false # NYI
UnpairedEntrances       : false # NYI
ShortenBowsersCastle    : false

# Randomization: Quizzes
RandomQuiz         : true
SkipQuiz           : false
QuizmoAlwaysAppears: false

# Randomization: Partner
PartnersInDefaultLocations: true
PartnersAlwaysUsable      : true
StartWithRandomPartners   : false
RandomPartnersMin         : 1 # 1-8
RandomPartnersMax         : 8 # 1-8
StartWithPartners: { # ignored if StartWithRandomPartners true
    Goombario : true,
    Kooper    : false,
    Bombette  : false,
    Parakarry : false,
    Bow       : false,
    Watt      : false,
    Sushie    : false,
    Lakilester: false
}

# Spoiler log
WriteSpoilerLog : true
PrettySpoilerlog: true

# Cosmetics / Palettes
Box5ColorA       : 0xEBE676FF # Status Bar Color A (main)
Box5ColorB       : 0x8E5A24FF # Status Bar Color B (shadow)
RandomCoinPalette: true
RomanNumerals    : false

# "*Setting" values explanation:
# DEFAULT_PALETTE = 0
# SELECT_PALETTE  = 1 (not for bosses or npcs)
# RANDOM_PICK     = 2
# ALWAYS_RANDOM   = 3
MarioSetting     : 0
MarioSprite      : 0
GoombarioSetting : 0
GoombarioSprite  : 0
KooperSetting    : 0
KooperSprite     : 0
#BombetteSetting  : 0
#BombetteSprite   : 0
#ParakarrySetting : 0
#ParakarrySprite  : 0
BowSetting       : 0
BowSprite        : 0
#WattSetting      : 0
#WattSprite       : 0
#SushieSetting    : 0
#SushieSprite     : 0
#LakilesterSetting: 0
#LakilesterSprite : 0
BossesSetting    : 0
NPCSetting       : 0

# Audio
TurnOffMusic: false