---
# OPEN WORLD PM64 SETTINGS
SettingsName   : Default Dev Preset
SettingsVersion: 0.1

# Options
StartingMap       : 0x00010104 # mac_00, Entry4
BlocksMatchContent: true
AlwaysSpeedySpin  : true
AlwaysISpy        : false
AlwaysPeekaboo    : false

InitialCoins : 50
CapEnemyXP   : true
NoXP         : false
2xDamage     : false
4xDamage     : false
OHKO         : false
NoSaveBlocks : false
NoHeartBlocks: false

# Pre-opened areas
FlowerGateOpen: false
BlueHouseOpen : false
ToyboxOpen    : false
WhaleOpen     : false

# Randomization: Logic
PlacementAlgorithm: ForwardFill
#PlacementAlgorithm: WeightedForwardFill # NYI
#PlacementAlgorithm: AssumedFill # NYI
#PlacementAlgorithm: CustomSeed
PlacementLogic: NoGlitches
#PlacementLogic: Glitches # NYI
#PlacementLogic: NoLogic

# Randomization: Difficulty
ShuffleChapterDifficulty: false
RandomFormations: false

# Randomization: Items
ShuffleItems          : true
IncludeCoins          : false
IncludeShops          : true
IncludePanels         : true
IncludeFavors         : false # Koopa Koot Favors
IncludeLetterChain    : false # true -> NYI
KeyitemsOutsideDungeon: false
KeyitemsOutsideChapter: true # "Keysanity" # false -> NYI

# Randomization: Moves and Badges
ShuffleBadgesBP: false
ShuffleBadgesFP: false
ShufflePartnerFP: false
ShuffleStarpowerSP: false

# Randomization: Entrances
ShuffleEntrances        : true  # NYI
ShuffleEntrancesByArea  : true  # NYI
ShuffleEntrancesByAll   : false # NYI
MatchEntranceTypes      : true  # NYI
RandomizeOnewayEntrances: false # NYI
UnpairedEntrances       : false # NYI

# Randomization: Quizzes
RandomQuiz: true
SkipQuiz  : false

# Randomization: Partner
PartnersInDefaultLocations: true
PartnersAlwaysUsable      : true
StartWithRandomPartners   : false # NYI
RandomPartnersMin         : 1     # NYI
RandomPartnersMax         : 8     # NYI
StartWithPartners: { # ignored if StartWithRandomPartners true
    Goombario : true,
    Kooper    : false,
    Bombette  : false,
    Parakarry : false,
    Bow       : false,
    Watt      : false,
    Sushie    : false,
    Lakilester: false
}

# Spoiler log
WriteSpoilerLog: true
PrettySpoilerlog: true

# Cosmetics / Palettes
ColorA: 0xEBE677FF # Box5ColorA
ColorB: 0x8E5A25FF # Box5ColorB
RandomCoinPalette: true

# Audio
TurnOffMusic: false